using Portfolio.Core.ProfileUser;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace Portfolio.APP.DTOs.ProfileDtos
{
    public class CreateProfileDto
    {
        [JsonIgnore] // Not needed for creation; generated by DB
        public Guid Id { get; set; }

        [Required(ErrorMessage = "Profile name is required.")]
        [StringLength(100, MinimumLength = 3, ErrorMessage = "Profile name must be between 3 and 100 characters.")]
        public string ProfileName { get; set; } = string.Empty;

        [Required(ErrorMessage = "Stack bio is required.")]
        [StringLength(500, ErrorMessage = "Stack bio cannot exceed 500 characters.")]
        public string StackBio { get; set; } = string.Empty;

        [Required(ErrorMessage = "Email address is required.")]
        [EmailAddress(ErrorMessage = "Invalid email format.")]
        public string EmailAddress { get; set; } = string.Empty;

        [Required(ErrorMessage = "Phone number is required.")]
        [Phone(ErrorMessage = "Invalid phone number format.")]
        public string PhoneNumber { get; set; } = string.Empty;

        [Url(ErrorMessage = "Invalid portfolio website URL.")]
        public string PortfolioWebsite { get; set; } = string.Empty;

        [Url(ErrorMessage = "Invalid profile image URL.")]
        public string ProfileImageUrl { get; set; } = string.Empty;

        [Url(ErrorMessage = "Invalid resume URL.")]
        public string ResumeUrl { get; set; } = string.Empty;

        // This should NOT be ignored if you expect it from the client
       // [JsonIgnore]

        [Required(ErrorMessage = "AppUserId is required.")]
        public Guid AppUserId { get; set; }

        // Navigation property should not be in a DTO
        [JsonIgnore]
        public AppUserDto? AppUser { get; set; }
    }
}
